name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
  compile:
    needs: [linux-unit-tests, windows-unit-tests]
    uses: salesforcecli/github-workflows/.github/workflows/externalCompile.yml@sm/external-compile
    with:
      packageName: '@salesforce/ts-types'
      externalProjectGitUrl: https://github.com/forcedotcom/sfdx-core
